"""
api/models/response.py
======================
Pydantic v2 response models for the Loan Approval API.

Responsibilities:
- LoanDecisionResponse: the primary success response for POST /api/v1/analyze
- AgentTraceResponse:   optional verbose response including per-agent traces
- ErrorResponse:        standardised error envelope for all 4xx/5xx responses
- HealthResponse:       GET /health liveness probe response

Design decisions:
- All response models are frozen (model_config frozen=True) so route handlers
  cannot accidentally mutate a response after construction.
- ErrorResponse is a separate Pydantic model (not a plain dict) so the
  Streamlit UI can always import and parse a typed response schema.
- AgentTraceResponse inherits LoanDecisionResponse and adds the trace fields
  so the base response is always a valid subset of the trace response.
"""

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Verdict type alias (re-used across response models)
# ---------------------------------------------------------------------------

VerdictType = Literal["APPROVED", "REJECTED", "REVIEW_REQUIRED"]


# ---------------------------------------------------------------------------
# Agent trace sub-model
# ---------------------------------------------------------------------------

class AgentTrace(BaseModel):
    """
    Captures the output of a single agent node for observability.

    Included in AgentTraceResponse when the caller requests verbose output.

    Attributes:
        agent_name:      Human-readable agent identifier.
        input_summary:   Brief description of what the agent received.
        output:          Raw output dict returned by the agent.
        latency_ms:      Wall-clock time the agent took to respond.
        skipped:         True if the node was bypassed (e.g. early rejection).
    """

    agent_name: str = Field(..., description="Agent identifier, e.g. 'applicant_profile_agent'")
    input_summary: str = Field(..., description="One-line summary of the agent's input context")
    output: dict[str, Any] = Field(..., description="Raw agent result dict")
    latency_ms: Optional[float] = Field(default=None, description="Agent wall-clock time in ms")
    skipped: bool = Field(default=False, description="True if this node was bypassed")

    model_config = {"frozen": True}


# ---------------------------------------------------------------------------
# Primary success response
# ---------------------------------------------------------------------------

class LoanDecisionResponse(BaseModel):
    """
    Primary response for a successful POST /api/v1/analyze call.

    Returned to the Streamlit UI and any downstream consumer of the API.

    Attributes:
        applicant_id:          Echoed from the request for correlation.
        verdict:               Final classification: APPROVED, REJECTED, or
                               REVIEW_REQUIRED.
        confidence_score:      Model's confidence in the verdict, 0.0–1.0.
                               Higher is more certain.
        explanation:           Plain-English rationale. Suitable for display
                               to a loan officer or the applicant.
        case_id:               Unique audit Case ID. Format: CASE-YYYYMMDD-NNNN.
                               Use this to look up the record in audit/logs/.
        notification_summary:  Applicant-facing notification text generated by
                               the Compliance Agent. None if compliance node
                               did not execute.
        risk_score:            Composite risk score 0–100 from the Financial
                               Risk Agent. None for early-rejection paths.
        credit_band:           Credit quality band from the Risk Agent.
        dti:                   Debt-to-income ratio calculated by Risk Agent.
    """

    applicant_id: str = Field(
        ...,
        description="Applicant ID echoed from the request.",
    )

    verdict: VerdictType = Field(
        ...,
        description="Final loan decision: APPROVED, REJECTED, or REVIEW_REQUIRED.",
    )

    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Decision confidence between 0.0 (uncertain) and 1.0 (certain). "
            "Scores >= 0.80 indicate a clear decision; 0.50–0.79 indicate "
            "a borderline REVIEW_REQUIRED case."
        ),
    )

    explanation: str = Field(
        ...,
        min_length=1,
        description=(
            "Human-readable rationale for the decision. References specific "
            "financial factors (DTI, credit score, income) per regulatory "
            "explainability requirements."
        ),
    )

    case_id: str = Field(
        ...,
        min_length=1,
        description="Unique audit Case ID. Format: CASE-YYYYMMDD-NNNN.",
    )

    notification_summary: Optional[str] = Field(
        default=None,
        description="Applicant-facing notification text from the Compliance Agent.",
    )

    # Risk metadata — included for UI display and observability
    risk_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=100.0,
        description="Composite risk score 0–100. Higher = more risky.",
    )

    credit_band: Optional[str] = Field(
        default=None,
        description="Credit quality band: excellent | good | fair | poor.",
    )

    dti: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Debt-to-income ratio (existing_liabilities / monthly_income).",
    )

    action_taken: str = Field(
        default="NO_ACTION_REQUIRED",
        description="Operational action selected for this case.",
    )

    notification_status: str = Field(
        default="NOT_SENT",
        description="Notification dispatch status for this case.",
    )

    review_queue: Optional[str] = Field(
        default=None,
        description="Assigned review queue for manual-review cases.",
    )

    manual_review_owner: Optional[str] = Field(
        default=None,
        description="Current owner handling manual review.",
    )

    reviewer_role: Optional[str] = Field(
        default=None,
        description="Role expected to process the manual review.",
    )

    review_due_timestamp: Optional[str] = Field(
        default=None,
        description="ISO 8601 due timestamp for manual review SLA.",
    )

    review_status: str = Field(
        default="NOT_REQUIRED",
        description="Manual-review lifecycle status for the case.",
    )

    status_transition: str = Field(
        default="NONE",
        description="Latest lifecycle transition label.",
    )

    transition_history: list[dict[str, str]] = Field(
        default_factory=list,
        description="Ordered lifecycle transition entries.",
    )

    model_config = {
        "frozen": True,
        "json_schema_extra": {
            "example": {
                "applicant_id":        "APP-2024-001",
                "verdict":             "APPROVED",
                "confidence_score":    0.87,
                "explanation":         (
                    "The applicant has a good credit score of 720, a low "
                    "DTI of 0.23, and stable salaried employment. All policy "
                    "criteria are satisfied."
                ),
                "case_id":             "CASE-20240115-0042",
                "notification_summary": (
                    "Congratulations! Your loan application has been approved. "
                    "A loan officer will contact you within 2 business days. "
                    "Your reference case ID is CASE-20240115-0042."
                ),
                "risk_score":   22.5,
                "credit_band":  "good",
                "dti":          0.225,
                "action_taken": "NO_ACTION_REQUIRED",
                "notification_status": "SENT_DISPLAY",
                "review_queue": None,
                "manual_review_owner": None,
                "reviewer_role": None,
                "review_due_timestamp": None,
                "review_status": "NOT_REQUIRED",
                "status_transition": "NONE",
                "transition_history": [],
            }
        },
    }


# ---------------------------------------------------------------------------
# Verbose trace response (extends primary response)
# ---------------------------------------------------------------------------

class AgentTraceResponse(LoanDecisionResponse):
    """
    Extended response that includes per-agent execution traces.

    Returned when the caller adds ?verbose=true to the analyze endpoint.
    Inherits all fields from LoanDecisionResponse and adds the trace list.

    Attributes:
        traces:        Ordered list of AgentTrace objects, one per executed node.
        total_latency_ms: End-to-end pipeline latency from API receipt to response.
    """

    traces: list[AgentTrace] = Field(
        default_factory=list,
        description="Per-agent execution traces, ordered by node execution sequence.",
    )

    total_latency_ms: Optional[float] = Field(
        default=None,
        description="End-to-end pipeline latency in milliseconds.",
    )

    model_config = {
        "frozen": True,
        "json_schema_extra": {
            "example": {
                "applicant_id":     "APP-2024-001",
                "verdict":          "APPROVED",
                "confidence_score": 0.87,
                "explanation":      "Strong credit and low DTI.",
                "case_id":          "CASE-20240115-0042",
                "total_latency_ms": 3240.5,
                "traces": [
                    {
                        "agent_name":    "applicant_profile_agent",
                        "input_summary": "age=35, salaried, income=800000",
                        "output":        {"valid": True, "employment_band": "stable"},
                        "latency_ms":    820.3,
                        "skipped":       False,
                    }
                ],
            }
        },
    }


# ---------------------------------------------------------------------------
# Error response
# ---------------------------------------------------------------------------

class ErrorResponse(BaseModel):
    """
    Standardised error envelope returned for all 4xx and 5xx responses.

    The Streamlit UI and API consumers always receive this shape on error,
    regardless of whether the error originated from Pydantic validation,
    a failed agent call, or an unexpected exception.

    Attributes:
        error:    Short machine-readable error code, e.g. VALIDATION_ERROR.
        message:  Human-readable description suitable for UI display.
        detail:   Optional technical detail for developer debugging (e.g.
                  exception class name). Omitted in production log output.
        field:    For validation errors, the specific field that failed.
    """

    error: str = Field(
        ...,
        description="Machine-readable error code identifier.",
        examples=["VALIDATION_ERROR", "INTERNAL_ERROR", "AGENT_TIMEOUT"],
    )

    message: str = Field(
        ...,
        description="Human-readable error description for UI display.",
        examples=["credit_score must be between 300 and 900"],
    )

    detail: Optional[str] = Field(
        default=None,
        description="Technical detail for debugging. Not shown in production UI.",
    )

    field: Optional[str] = Field(
        default=None,
        description="The specific request field that caused a validation error.",
        examples=["credit_score", "loan_amount"],
    )

    model_config = {
        "frozen": True,
        "json_schema_extra": {
            "example": {
                "error":   "VALIDATION_ERROR",
                "message": "credit_score must be between 300 and 900",
                "detail":  None,
                "field":   "credit_score",
            }
        },
    }


# ---------------------------------------------------------------------------
# Health check response
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """
    Response for the GET /health liveness probe endpoint.

    Attributes:
        status:  "ok" when the service is healthy.
        service: Service identifier string.
        version: API version string from settings.
    """

    status: Literal["ok", "degraded", "error"] = Field(
        ...,
        description="Service health status.",
    )

    service: str = Field(
        ...,
        description="Service identifier.",
        examples=["loan-approval-api"],
    )

    version: str = Field(
        default="1.0.0",
        description="API version.",
    )

    model_config = {
        "frozen": True,
        "json_schema_extra": {
            "example": {
                "status":  "ok",
                "service": "loan-approval-api",
                "version": "1.0.0",
            }
        },
    }
